//Rest client extension
//Create a user
POST http://localhost:5000/groups
Content-Type: application/json
{
  "name": "Município de Braga",
  "title": "Carta Regime de Uso do Solo",
  "description": "Carta do Regime de Uso do Solo - Redondo. Informação extraída da Planta de Ordenamento do PDM em vigor com aplicação da classificação e qualificação do solo estabelecida no Decreto Regulamentar n.º 15/2015 de 19 de agosto. Gestão efetuada pela DGT."
}
